#!/usr/bin/env bash
# Displays the timer for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

h=0

while [ $h -lt 13 ]; do
      echo "Hour: $h"
      i=1
      while [ $i -le 59 ]; do
      	  echo "$i"
	  i=$((i+1))
      done
      h=$((h+1))
done
